### ISSUE TITLE
New headers and new special character suggestions

### ISSUE THREAD

**Issue by Mintsoda15** [RPGHacker/SMW-Workspace#18]
New header
.header
db $aa
db %bbbbbccc,%ccddddee,%eeffffgg,%gghhhhhh,$ii,%jjjj _αβγδ_
dw $kkkk,$llll
db %mnnnop-q
db %rrssttuu,$vv,$ww,$xx,$yy
_db $zε
dw $ζζζζ,$ηηηη,$θθθθ
dw $ιιιι_

αβγδ = Change frame style, change background style, change frame color, change background color
      0 = not change, 1 = change
z = Textbox frame style
ε = Background Style, If αβ is 00, this row is omitted.
ζζζζηηηηθθθθ = Textbox frame color, If γ is 0, this row is omitted.
ιιιι = background color, If δ is 0, this row is omitted.

New special character
<del>**$EB**</del>
<del> Level end(Without event)</del>
<del>**$EA**</del>
<del> Secret Exit(No walk)</del>
<del>**$E9**</del>
<del> Normal Exit(No walk)</del>
<del> **$E8**</del>
**$E9**
 Sprite text, It appears as normal text, except that it is a sprite.
db $E8,%YXPPCCCT,$xx,$yy
YXPPCCCT : https://www.smwcentral.net/?p=viewthread&t=25106
xx : Tile number
yy : width
ex:
`db $E8,%00111010,$26,$10," This is Flower",$FA,$FF`
 ↓
🌼 This is Flower
(🌼 is displayed as a sprite tile.)

**Comment by RPGHacker** [comment]
Most of these features sound like good ideas and should be reasonably simple to add. The only thing that I don't think will be possible in the patch is the sprite command. Getting sprites on top of the text box is only possible by changing layer priority settings and moving sprites in front of of layer 3, which would of course affect all sprites. I've already tried to implement the cursor used in choices as a sprite, but eventually gave up on it because it wasn't feasible and instead went with a slightly complicated solution of merging it with the text on layer 3. Sprites would only really be possible for text boxes without a background, but for me personally that's too restrictive to consider as a feature.

**Comment by ExE-Boss** [comment]
Also, for the level end, I’d prefer to avoid adding 3 commands, and instead extend an existing command (like the current exit one for example).

**Comment by HayashiNeru** [comment]
[https://bin.smwcentral.net/u/31439/SPRITEVWF%2528...%2529.png](url)
Is this displayed?

**Comment by RPGHacker** [comment]
You mean a bit to change the priority for the entire layer?

**Comment by HayashiNeru** [comment]
yes.

**Comment by RPGHacker** [comment]
I guess that would be possible, as long as there is some way of restoring the previous priority settings after a dialog ends.

**Comment by RPGHacker** [comment]
For me personally, the backwards compatibility is just nice-to-have in this case, since the upgrade is optional and people can likely work fine with the old version still, plus most hacks probably don't have all that much text, making it reasonably simple to fix texts manually. That being said, if we can accomplish backwards-compatibility, then yeah, that would of course be a bonus.

**Comment by HayashiNeru** [comment]
I think it is not expected there is a problem backwards compatibility.
Because
[Suggested new header]
`.header
db $aa
db %bbbbbccc,%ccddddee,%eeffffgg,%gghhhhhh,$ii,%jjjjαβγδ
dw $kkkk,$llll
db %mnnnopωq
db %rrssttuu,$vv,$ww,$xx,$yy
db $zε
dw $ζζζζ,$ηηηη,$θθθθ
dw $ιιιι`

[Existing header]
`.header
db $aa
db %bbbbbccc,%ccddddee,%eeffffgg,%gghhhhhh,$ii,%jjjj----
dw $kkkk,$llll
db %mnnnop-q
db %rrssttuu,$vv,$ww,$xx,$yy`

The dash part (unused) is 0 in existing headers.
The added three lines are only active if the bit that was not used in the existing header is 1.
So, in the existing header, the αβγδ part and the ω part are 0, so there is nothing wrong with the new header.

Also, in the case of special characters, the probability of writing the characters after E8 is very low, which seems to be no problem.
For Japanese, the 16-bit mode is also used.
Of course, there is no guarantee that a small number of exceptions.

**Comment by HayashiNeru** [comment]
I'm very sorry to have to write again in 9 days, but can I change my suggestion?
**$EB**
 Level end
$EB,$XX
XX = 00-77 : Overworld event
XX = 7D : Normal Clear
XX = 7E : Secret Clear
XX = 7F : No event
**$EA**
Change text layout. (Also applies to the next line.)
$EA,$00 : Left layout
$EA,$01 : Center layout
$EA,$02 : Right layout

**Comment by RPGHacker** [comment]
Don't worry, no anti-bump rules or anythng like that on GitHub. ;)
And yeah, those suggestions make sense as well.

**Comment by HayashiNeru** [comment]
ok. thank you.

**Comment by RPGHacker** [comment]
A new `!exit_to_ow()` command will be available in the next version of VWF Dialogues, which pretty much includes all the functionality suggested in the opening post here.

I still have no great ideas for how to make a sprite command work nicely with the patch, and I'm not fully sold on the priority solution, since it feels like quite a hackaround to me. Rejected for the time being.

I think changing text layouts mid-message is currently out-of-scope for the patch. It's pretty much built around only using one text layout per message box, and I think changing that would require massive patch rewrites. So also rejected for the time being. However, right-aligned text (via the message header) might be added in a future version of the patch, since that should very well be possible.
