### ISSUE TITLE
[BUG] [VWF Dialogues] Incompatibility with Remove Status Bar

### ISSUE THREAD

**Issue by MarioFanGamer** [RPGHacker/SMW-Workspace#23]
This actually applies to multiple patches with a custom status bar including Minimalist Status Bar, SMB3 Status Bar and DKCR Styled Status Bar (Super Status Bar is, by hijacks alone, fortunately compatible).

Basically, VWF Dialogues's v-blank code assumes the code where the status bar tilemap is uploaded is untouched since it jumps to that location when custom status bars either repurpose it for freespace (Minimalist Status Bar, SMB3 Status Bar) or simply remove it altogether (Nuke Status Bar, DKCR Styled Status Bar).

On an aside, return code can be better handled by directly returning to $0081F7 onto the stack instead of executing a JSL2RTS on top of that carry is untouched in the return code (since the processor flags are preserved), making the `LDA $0D9B : LSR` unnecessary.

**Comment by RPGHacker** [comment]
Fixed via commits e96e3ed5044ff9bdfdcf2b486224c2ab24bb9b38 and 585cf449bf0b116fc2b6037a69eaa10a2d6de08d. SMB3 and Minimalist in particular were absolute hell to get working. They, along with Remove Status Bar, now have some new compatibility settings in vwfconfig.cfg, since I couldn't achieve full compatibility without specialized compatibility hacks.
